package SupportingObjects;

public enum Token {
    ANOTHER, ALMOST, ARRIVE, BENCH, CLIMB, DICES,
    GOTOSLEEP, INN, MOVEAGAIN,
    PARKINGTERM, PICKACARD, RETREAT, SLICE,
    SPRING, STANDARD, STANDSTILL,
    THROW, THROWAGAIN, WIN;
}
